# Generated by Django 5.2.7 on 2025-10-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('methode_valorisation', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('MOY', 'Moyenne pondérée')], default='FIFO', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateField()),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=12)),
                ('quantite', models.IntegerField()),
                ('prix_vente_unitaire', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('quantite_initiale', models.IntegerField()),
                ('quantite_restante', models.IntegerField()),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=6, max_digits=14)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_allouee', models.IntegerField()),
                ('prix_cout_unitaire', models.DecimalField(decimal_places=6, max_digits=14)),
                ('mouvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stock.mouvement')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='stock.stock')),
            ],
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['produit', 'date_mouvement'], name='stock_mouve_produit_6d3c07_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['type'], name='stock_mouve_type_891264_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['produit', 'date_entree'], name='stock_stock_produit_0aa2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationsortie',
            index=models.Index(fields=['mouvement'], name='stock_alloc_mouveme_a5dad7_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationsortie',
            index=models.Index(fields=['lot'], name='stock_alloc_lot_id_5d94d5_idx'),
        ),
    ]
