# Generated by Django 5.2.7 on 2025-10-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='methode_valorisation',
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MvtStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField()),
                ('sens', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
            options={
                'verbose_name': 'MvtStock',
                'verbose_name_plural': 'MvtStocks',
            },
        ),
        migrations.DeleteModel(
            name='AllocationSortie',
        ),
        migrations.DeleteModel(
            name='Mouvement',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
